### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by gazjoy** [nhsbsa/frontend-toolkit#10]
## What
> Give a brief description of the style, component or pattern you want to propose.

This may seem like a duplicate of the Table pattern in the GOV design system but it isn't. For the table I am referring to a pattern which makes a table behave nicely on a mobile sized screen. I'm not sure if we want to be more specific with that on the issue name, "responsive table"?

Small
![localhost_3000_statement_schemeReference=2008 schemeYear=2007_2008(iPhone 5_SE)](https://user-images.githubusercontent.com/628064/65526012-4e5ce300-dee8-11e9-8be9-006c133bce64.png)

Medium
![localhost_3000_statement_schemeReference=2008 schemeYear=2007_2008(iPad)](https://user-images.githubusercontent.com/628064/65526021-50bf3d00-dee8-11e9-8544-d1ceb3a2ae25.png)

Large
![localhost_3000_statement_schemeReference=2008 schemeYear=2007_2008](https://user-images.githubusercontent.com/628064/65526046-574db480-dee8-11e9-8e85-bb15f9e7e77b.png)

## Why
> Explain why you think this should be added to the BSA Design System.

This is useful for larger tables which need to be displayed on smaller screens. Most NHS Trusts and businesses have very long names which need to be displayed for example: "Birmingham and Solihull Mental Health NHS Foundation Trust".

> - What evidence do you have that it's needed?

Users need to be able to access our service on a mobile device.

> - What evidence do you have that it meets the needs of the users of BSA services?

For the pensions service we have to show a history of pension membership. These memberships can be very complicated and overlap. The simplest way to represent this visually at the minute is to use a table. However the information does not read well on smaller screens without the addition of the responsive table code.

> - Have you checked that it doesn't already exist in the GOV.UK Design System or BSA Design System? 

A table does exist in the GOV.UK design system but not a responsive one.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

Our CSS https://github.com/nhsbsa/nhs-pension-prototype-swoosh/blob/master/app/v6/assets/sass/components/_responsive-table.scss

We have initially used the code from here: https://github.com/Fenwick17/responsive-tables
 with a few minor tweaks for our needs.

**Comment by helenspires** [comment]
Added to https://github.com/nhsbsa/design-system/issues/17
