### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by gazjoy** [nhsbsa/frontend-toolkit#16]
## What

A card is a visual unit, usually taller than it is wide. It is similar in ratio to a playing card. A card is not to be confused with other units which are wider than they are tall, known as media units or flags.

Also known as, panel, promo.

Example: 
![image](https://user-images.githubusercontent.com/628064/65894860-629a5780-e3a2-11e9-8e36-9f2b235a94e5.png)

## Why
> Explain why you think this should be added to the NHS BSA Design System.

Cards exist in lots of other guises across NHS and Government services. If the GDS design system or NHS Digital Service manual don't do the job we need them to do then we need to track our own usage.

> - What evidence do you have that it's needed?
On NHS Pensions members of the scheme can have multiple pensions schemes each with different actions associated to them. We originally had these grouped together but users found this very confusing. By splitting the schemes with the card pattern and assigning actions in the card we found users were able to make more sense of the information they were given.

> - What evidence do you have that it meets the needs of the users of NHS BSA services?
We have good feedback from pensions members that they understood that they were part of more than one pension when we split the schemes from just a single page view.

> - Have you checked that it doesn't already exist in the NHS Digital Service Manual, GOV.UK Design System or NHS BSA Design System? 

The card pattern is a "to-do" component on the GOV.UK Design system Community backlog: https://github.com/alphagov/govuk-design-system-backlog/issues/113
However as it is not yet an approved pattern I think it is worth tracking the use of it within BSA here.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

NHS Digital Service Manual has a version called "Panel" https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/159

Also NHS Digital Service Manual has a version called "Promo" https://github.com/nhsuk/nhsuk-frontend/issues/176

– would we just use these? Are they accessible? I have heard (not directly from users) but from stakeholders that they like to copy and paste text from the browser. Using the NHS Digital "promo" link component would inhibit this, is this a concern?

**Comment by helenspires** [comment]
moved to https://github.com/nhsbsa/design-system/issues/18
