### ISSUE TITLE
Currency input

### ISSUE THREAD

**Issue by gazjoy** [nhsbsa/frontend-toolkit#7]
## What
To give users a clear indication of the amount entered in pounds.

![image](https://user-images.githubusercontent.com/628064/56735022-48f24580-675c-11e9-95d3-93e5fff4706e.png)

## Why
In certain scenarios we want to capture an amount in pounds. Users are used to having an amount that corresponds with the symbol and gives assurance of what the value is.

## Anything else
The GDS design system team are also tracking this:
_https://github.com/alphagov/govuk-design-system-backlog/issues/68_

HMCTS have a terrific version which could remove any ambiguity of users potentially trying to delete the symbol before entering the value.

- _https://github.com/hmcts/design-system-backlog/issues/32_
- _http://hmcts-design-system.herokuapp.com/components/currency-input_

**Comment by helenspires** [comment]
moved to https://github.com/nhsbsa/design-system/issues/10
